workflows:
  default-workflow:
    name: Default workflow
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      # - name: Run Flutter tests
      #   script: |
      #     flutter test
      - name: Build APK
        script: |
          flutter build apk --release
      - name: Build iOS
        script: |
          flutter build ios --release
    artifacts:
      - build/**/outputs/**/*.apk
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - claudio.junior@bairesdev.com