workflows:
  my-workflow:
    name: Basic Flutter Workflow (develop)

    environment:
      vars:
        # Read Codemagic' environment variables
        KEY_PASSWORD: $KEY_PASSWORD
        KEY_ALIAS: $KEY_ALIAS
        SECRET_TOKEN: $SECRET_TOKEN
        OPEN_KEY: $OPEN_KEY

    scripts:
      - name: Show Private Environment Variables
        script: |
          echo "Codemagic Mac Mini envVars"
          echo "API Key: $KEY_PASSWORD"
          echo "Key Store PW: $KEYSTORE_PASSWORD"
          echo "Key Alias: $KEY_ALIAS"
          echo "$printenv"
      - name: Show Non-Private Environment Variables
        script: |
          echo "Open Key: $OPEN_KEY"
          echo $printenv