workflows:
  default-workflow:
    name: Default workflow
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      # Add scripts here
    artifacts:
      - build/**/outputs/**/*.apk
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - name@example.com  
  
  # web-workflow:
  #   name: Web Workflow
  #   instance_type: linux_x2
  #   environment:
  #     groups:
  #       - cloudflare # <-- (Includes CLOUDFLARE_API_TOKEN, CLOUDFLARE_ACCOUNT_ID)
  #     flutter: stable
  #   scripts:
  #     - name: Get Flutter packages
  #       script: flutter packages pub get
  #     - flutter config --enable-web
  #     - name: Build Web
  #       script: | 
  #         flutter build web --release
  #     - name: Gather the web files
  #       script: | 
  #         cd build/web
  #         7z a -r ../web.zip ./*
  #   artifacts:
  #     - build/web.zip
  #   publishing:
  #     scripts:
  #       - name: Install wrangler
  #         script: npm install -g wrangler
  #       - name: Deploy to Cloudflare Pages
  #         script: | 
  #           wrangler pages publish build/web/ --project-name my-flutter-pages --branch production
  #     slack:
  #       channel: "#builds"
  #       notify_on_build_start: true
  